name = input("Enter a your name: ")
nickname = input("Enter your nickname: ")
travel = input("Enter a your travelling place: ")
food = input("Enter your favourite food: ")
dream = input("Enter your dream,you want to become: ")
print("Welcome in Mad Libs Game !! "  +name )
print("Friends call you "  + nickname)
print("You like to travel "  + travel)
print("Your favourite food is "  + food)
print("Your dream is  to become"  + dream)
print("Thanks for your good time!! see you again!!")
